baseURL = "https://www.example.com/"  # Replace with your actual base URL
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
staticDir = ["static", "themes/Niello/static"]
theme = "Niello"

[languages]
  [languages.en]
    title = "{MoGo Blogging} - Discover Issues, Share Solutions."
    languageCode = "en-us"
    LanguageName = "🇺🇸EN"
    contentDir = "content/en"
    weight = 1
    [[languages.en.menus.main]]
      name = 'Home'
      pageRef = '/'
      weight = 1
    [[languages.en.menus.main]]
      name = 'Categories'
      pageRef = '/categories'
      weight = 2
    [[languages.en.menus.main]]
      name = 'Tags'
      pageRef = '/tags'
      weight = 3
    [[languages.en.menus.main]]
      name = 'Contact'
      pageRef = '/contact'
      weight = 4

[params]
  [params.bannershowcase]
    categories = ["Design"]
    limit = 2
  [params.email]
    contact = "meevans111@gmail.com https://github.com/ManoloEvans"
    linkedin = "https://www.linkedin.com/in/manoloevans"
  [params.ignore]
    categories = ["privacy", "terms", "archives", "cookie", "contact"]
  [params.license]
    copyright = "&#xA9; 2025 by Manolo Evans. All Rights Reserved."
  [params.share]
    sharethis = "******"  # Optional, add your ShareThis app ID here
  [params.disqus]
    shortname = "******"  # Optional, Disqus Short Name

[outputs]
  home = ["HTML", "JSON"]